pipeline{
    timestamps {
        agent { node { label 'AmitPC' } }
        stages{
            stage('TestTimeStemp'){
              powershell """ write-host "Amit" """
            }
        }
    }
}
