pipeline {
    agent { node { label 'AmitPC' } }
     stages {
         timestamps {
        stage('Pre Build Step') {
            steps {
                powershell'''write-host "Amit" '''
                 
            }
        }
     }
    
}
