pipeline{ 
        agent { node { label 'AmitPC' } }
        stages{
            stage('TestTimeStemp'){
                timestamps {
                    powershell """ write-host "Amit" """
                }
              
            }
        }
    
}
